<?php

declare(strict_types=1);

/**
 * This file is a part of Drupal Headless App.
 *
 * @author Muhammed Naushad <muhammed.naushad@ekino.com>
 * @copyright Copyright (c) Ekino. All rights reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @file
 * Primary module hooks for app_attribute module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
/**
 * Implements hook_theme().
 */
/**
 * @return array<mixed>
 */
function app_attribute_theme(): array
{
  return [
    'attribute_add_list' => [
      'variables' => ['content' => NULL],
    ],
  ];
}
